# Configuracoes especificas para rodar na sua maquina
spring.datasource.url=jdbc:h2:mem:gerenciador_local
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console para voce ver as tabelas
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update


# Configuração do broker (exemplo local)
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=app-local
mqtt.username=
mqtt.password=

mqtt.enabled=true
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30
mqtt.default-qos=1

mqtt.ssl.enabled=false
mqtt.ssl.protocol=TLS
mqtt.ssl.trust-store-location=classpath:certs/broker-truststore.p12
mqtt.ssl.trust-store-password=changeit
mqtt.ssl.trust-store-type=PKCS12

mqtt.ssl.trust-certificate-location=classpath:certs/emqxsl-ca.crt
mqtt.ssl.trust-certificate-format=AUTO

mqtt.ssl.key-store-location=classpath:certs/client-keystore.p12
mqtt.ssl.key-store-password=changeit
mqtt.ssl.key-store-type=PKCS12
mqtt.ssl.key-password=changeit

mqtt.logs.registry=true
mqtt.logs.subscription=true
mqtt.logs.publish=true
mqtt.logs.receive=true
mqtt.logs.payload=false
mqtt.logs.dispatch=true
mqtt.logs.invocation=true
