# ==========================================
# Perfil de Produção (PostgreSQL na Render)
# ==========================================
# O Spring vai ler estas variáveis de ambiente que serão injetadas pela Render
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Dialeto correto para o Hibernate otimizar as queries para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Em produção, a melhor prática é usar uma ferramenta de migração como o Flyway,
# mas como ainda estamos a usar o Hibernate para gerar o esquema, usamos 'update' com cautela.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false