spring.application.name=dmmps-gerenciador-de-ferramentas-backend

# Define que o profile 'local' é o ativo por padrão
spring.profiles.active=local

api.security.token.secret=chave_secreta_dmmps_2026_mudar_em_prod