spring.application.name=dmmps-gerenciador-de-ferramentas-backend
# Define que o profile 'local' é o ativo por padrão
spring.profiles.active=local
# JWT
api.security.token.secret=${JWT_SECRET:dmmps-secret-local}