# Configurações específicas para rodar na sua máquina
spring.datasource.url=jdbc:h2:mem:gerenciador_local
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console para você ver as tabelas
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update


# Configuração do broker (exemplo local)
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=app-local
mqtt.username=
mqtt.password=
